owner: sannidhyaroy # Your GitHub organization or username, where this repository lives
repo: Uptime-Ryuu # The name of this repository

sites:
  - name: Authelia
    url: $AUTH_URL
  - name: Gitea
    url: $GITEA_URL
  - name: Immich
    url: $IMMICH_URL
  - name: Jellyseerr
    url: $JELLYSEERR_URL
  - name: Komga
    url: $KOMGA_URL
  - name: Nextcloud
    url: $NEXTCLOUD_URL
  - name: Paperless
    url: $PAPERLESS_URL
  - name: Soduto
    url: $SODUTO_URL
  - name: Vaultwarden
    url: $VAULTWARDEN_URL
  - name: Velocity Search
    url: $VELOCITY_URL
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

assignees: # Users to assign downtime issues (optional)
  - sannidhyaroy

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.thenoton.com
  # baseUrl: /your-repo-name
  logoUrl: https://uptime.thenoton.com/upptime-icon.svg
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Ryuu
  introTitle: "**Uptime Ryuu**, the fancy monitoring tool for Team NOTON"
  introMessage: Uptime Monitoring Solution for Team NOTON, backed by the open-source project [Upptime](https://github.com/upptime/upptime), powered entirely by GitHub
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
